# Generated by Django 5.1.6 on 2025-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
