# Generated by Django 5.1.6 on 2025-02-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
