# Generated by Django 5.1.6 on 2025-02-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_resume_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
