# Generated by Django 5.1.6 on 2025-04-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0005_alter_resume_options_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
